### ISSUE TITLE
Greyscale only works partly

### ISSUE THREAD

**Issue by hno2** [weskamm/ol3vectortiles#1]
For me the "Render grayscale" checkbox seems to work partly, since only the upper left forth of the map seems to be in Gray 
![grey](https://cloud.githubusercontent.com/assets/436990/6754566/b595b4c8-cf1d-11e4-939e-f087deb7fd4b.png)
![color](https://cloud.githubusercontent.com/assets/436990/6754565/b594c02c-cf1d-11e4-8d4c-9d341d039f95.png)

System (Chrome Version 41.0.2272.89 (64-bit) on Mac OSX 10.10.2)

**Comment by weskamm** [comment]
Thanks for your feedback! I wasn't able to reproduce that behaviour on chrome 41 64bit on linux and windows, so i have no real chance of fixing this. If this functionality is important to you i highly advise you to just create a new style with grey colors. 

The current "implementation" is just for demo purposes, seems to be unreliable at least for you and is a bad choice performance wise, as the map gets rerendered in greyscale after it has been drawn with colors.

As i said, if you rely on a function like this, just create / duplicate the current style and adjust the colors to your needs. For now i won't change the code, as i have no option to reproduce this behaviour.
